// Cards Against Sobriety: original black (prompt) and white (answer) cards.
// "___" marks a blank; a black card with two blanks asks for two white cards.
// Filthy cards are only dealt in filthy mode.

export const BLACK_MILD = [
  "What's that smell?",
  "What's the real reason I'm always late?",
  "The next Bake Off showstopper: ___.",
  "What did I find in the back of my nan's cupboard?",
  "The secret to a happy marriage is ___.",
  "What's ruining Britain?",
  "My therapist says I need to stop ___.",
  "Tonight on Crimewatch: ___.",
  "What got me banned from the Harvester?",
  "Coming soon to Netflix: a gritty drama about ___.",
  "My New Year's resolution is to give up ___.",
  "What's the King's guilty pleasure?",
  "Step one: ___. Step two: profit.",
  "What's the worst thing to bring to a christening?",
  "What will aliens think of us when they find ___?",
  "What got the whole group chat muted?",
  "Instead of a stag do, we're doing ___.",
  "The only thing I miss about school is ___.",
  "What's keeping the Queen Vic open?",
  "What did the vicar confiscate?",
  "My ideal Sunday: roast dinner, a nap and ___.",
  "What would Jesus do?",
  "What ended the Christmas truce in our house?",
  "Why can't I sleep at night?",
  "In a shocking twist, Love Island is now about ___.",
  "I'm not saying it was ___, but it was ___.",
  "What's my superpower?",
  "What's in the Greggs secret menu?",
  "Blue Peter's latest badge is for ___.",
  "The Olympics just added ___ as an event.",
  "Why did I get sent home from work?",
  "Scientists have finally discovered a cure for ___.",
  "What's the worst thing to hear from the next cubicle?",
  "What ruined the school nativity?",
  "Mum, I need to tell you something. It's about ___.",
  "The Wetherspoons app now lets you order ___ to your table.",
  "What's the one thing you never want to see at a wedding?",
  "What did I buy at 3am on Amazon?",
  "Welcome to my TED talk about ___.",
  "In the future, pubs will serve ___ instead of beer.",
  "___: the reason we can't have nice things.",
  "What's the best way to end a first date?",
  "What does my dog think about when I'm at work?",
  "Brexit: we were promised ___, and we got ___.",
  "What's hidden in the Houses of Parliament basement?",
  "Dear diary, today I ___.",
  "Why is there a police cordon around the Wetherspoons?",
  "The only thing that can bring this family together is ___.",
  "It's not a party until someone brings ___.",
  "What's the worst thing to say at a job interview?",
  "What's Santa's dirty little secret?",
  "Why is Uncle Terry not allowed at family events anymore?",
  "What made the pub quiz get violent?",
  "My life flashed before my eyes. It was mostly ___.",
  "What's the best thing about being British?",
  "What's the worst thing to find in a hotel bed?",
  "The Landlord's last words: ___.",
  "Tonight's special at the chippy: ___ in batter.",
  "What's the real reason the Tube is delayed?",
  "What did I do on my gap year?",
  "What do old people talk about when we're not around?",
  "What made the Bake Off tent go silent?",
  "In 2050, the national anthem will be about ___.",
  "What's going to kill me first?",
  "My dating profile says I love long walks and ___.",
  "The only rule at this party: no ___.",
  "What's the worst possible thing to put in a time capsule?",
  "Here's a tip: never mix ___ and ___.",
  "What's my Mastermind specialist subject?",
  "The next big fitness craze: ___.",
];

export const BLACK_FILTHY = [
  "What's my safe word?",
  "What's the one thing I won't do in bed?",
  "My OnlyFans is mostly ___.",
  "What did my ex leave behind?",
  "What's the worst thing to shout during sex?",
  "Why did I get kicked out of the swingers' party?",
  "The new Ann Summers bestseller: ___.",
  "What's in my browser history?",
  "Sex tip: before you start, always ___.",
  "What happened on the stag do stays on the stag do. Except ___.",
  "My body count is low, but my ___ count is high.",
  "What's the real reason I'm single?",
  "What did I find on my partner's phone?",
  "What got me banned from Tinder?",
  "Foreplay, for me, is mostly ___.",
  "What ruined the orgy?",
  "In the bedroom, I like to be called ___.",
  "What made the hot tub go cloudy?",
  "What's going on in the disabled toilet at the club?",
  "The morning after, all I remember is ___.",
  "Love Island's new challenge: ___.",
  "What do I think about while having sex?",
  "My walk of shame included ___.",
  "What's the worst thing to find in your partner's bedside drawer?",
  "The best part of waking up is ___ in your bed.",
  "What's my porn star name?",
  "What will I be telling the STI clinic?",
  "I knew it was over when she said ___.",
  "I knew it was over when he said ___.",
  "What's the worst thing to hear through the wall of a Premier Inn?",
  "Only fans? More like only ___.",
  "What's in the Landlord's secret drawer?",
  "What's making my nan blush?",
  "My kink is ___, and my other kink is ___.",
  "What's the real reason I'm limping?",
  "The mile-high club now requires ___.",
  "What should never be done in a hot tub?",
  "Tinder bio: 6'2\", loves travel and ___.",
  "What did I do at the Christmas party that HR wants to talk about?",
  "What's the one thing you shouldn't lick?",
  "What's making the neighbours complain?",
  "Guys, I did something weird last night. I ___.",
  "What's the worst thing to have in your pocket when you get arrested?",
  "The theme of our first threesome: ___.",
  "What's really going on at the vicar's house party?",
  "My doctor says my ___ is 'worryingly large'.",
  "What's in my nudes folder?",
  "Why did the stripper leave in tears?",
  "What would get you kicked out of Butlin's?",
  "The perfect first date: ___, followed by ___.",
];

export const WHITE_MILD = [
  "A soggy Greggs sausage roll", "My nan's WhatsApp voice notes", "A pigeon with a grudge", "Crying in a Tesco car park",
  "The entire cast of EastEnders", "An aggressively sincere birthday card", "Forty pints of Stella", "A haunted Toby Carvery",
  "Wetherspoons at 9am", "A very confident seagull", "Gordon Ramsay's disappointment", "Pretending to be busy",
  "A Nokia 3310 that still works", "The self-checkout saying 'unexpected item'", "A lukewarm cup of tea", "Being British about it",
  "Queueing for no reason", "An emotional support ferret", "The last Pringle", "A 45-minute voicemail",
  "Dad dancing", "A disappointing fireworks display", "The Loch Ness Monster's OnlyFans", "Accidentally waving at someone who wasn't waving at me",
  "Being sick on a pedalo", "A traffic cone on a statue", "A lifetime ban from Nando's", "Premier Inn breakfast",
  "Sunburn in the shape of a vest", "A stag do in Magaluf", "A scotch egg of questionable age", "Micky Flanagan",
  "Brexit", "Too many Jägerbombs", "The Crazy Frog", "A tax return filed at 11:59pm",
  "Reply-all", "A child's drawing of the teacher", "The man from the Go Compare advert", "A wasp at a picnic",
  "The group chat", "Accidentally calling the teacher 'Mum'", "An inflatable flamingo", "Mild Irish dancing",
  "The Chuckle Brothers", "Spilling a pint on the pub dog", "A Blue Peter badge", "Cheesy chips at 3am",
  "A really long wee", "My dad's opinions", "An ex's Netflix password", "The smell of the Tube",
  "A Tamagotchi graveyard", "Karaoke Bohemian Rhapsody", "Deciding to 'just have one'", "A strongly worded letter to the council",
  "Monday morning", "Passive-aggressive Post-it notes", "Someone clapping when the plane lands", "Losing a flip-flop in the sea",
  "The Year 9 disco", "An ironic Crocs phase", "A Fruit Shoot", "The squeaky wheel on every trolley",
  "A lovely bit of cheese", "Emotional damage", "Pretending to understand wine", "A ghost who just wants a cuppa",
  "Uncle Terry's conspiracy theories", "A wrong turn in IKEA", "The King", "My flatmate's mysterious boyfriend",
  "Fifteen missed calls from Mum", "Being too hungover for Sunday lunch", "A goat in a jumper", "Losing my phone in my own hand",
  "A horse that has simply had enough", "A leaflet about pensions", "The chippy owner's secret family", "Crying at John Lewis adverts",
  "Getting stuck in a revolving door", "A fire drill in the rain", "An overly competitive game of Monopoly", "The bus that never comes",
  "A pub quiz team called 'Quiz Team Aguilera'", "The office microwave", "Screaming into a pillow", "Hiding from the neighbours",
  "Heinz Beanz on everything", "A spirited debate about scones", "A lanyard with too many keys", "Bread sauce",
  "A vicar on a skateboard", "Leaving without saying goodbye", "The Wi-Fi password written on a napkin", "An unsolicited PowerPoint",
  "Existential dread", "A dog that can open the fridge", "Eating cereal for tea", "The nostalgic smell of Lynx Africa",
  "Accidentally joining a cult", "A really good nap", "My mate's band", "The bouncer's life story",
  "Two-for-one on Pinot Grigio", "A disappointing Christmas cracker joke", "The smoke alarm at 4am", "A casserole of regret",
  "The seagull that stole my chips", "Pretending not to be in", "A tragically short fringe", "An extremely large jacket potato",
  "An unnecessary road trip to Skegness", "The pub dog", "A pensioner with a drone", "My search history",
  "Being dumped by text", "A rogue sprout", "The 'fun' teacher", "Accidentally sending a voice note",
  "A lukewarm bath", "Morris dancers", "A stuffed badger", "Shouting 'is this seat taken?'",
  "Being asked for ID at 35", "A crisp sandwich", "The Tube at rush hour", "An inappropriate eulogy",
  "The world's saddest buffet", "My mum finding out", "Saying 'you too' to the waiter who said 'enjoy your meal'", "A very long receipt",
  "The Only Fools and Horses theme tune", "An unfortunate tan line", "A spaniel in a cagoule", "A drunk text to the landlord",
  "The worst best man in history", "A tax inspector at a rave", "Unexpected bagpipes", "The sausage from the full English",
  "A small but loud child", "The final episode of Neighbours", "Poor life choices", "A hen do in matching T-shirts",
];

export const WHITE_FILTHY = [
  "A sex swing in the conservatory", "Accidentally sexting my nan", "Morning glory", "An awkward threesome",
  "Handcuffs with no key", "A very sticky hotel duvet", "Getting caught by the neighbour's Ring doorbell", "The walk of shame in a wedding dress",
  "A Premier Inn at 3pm on a Tuesday", "Faking it", "A disappointing willy", "My ex's mum",
  "A lap dance from someone's dad", "An enthusiastic vibrator", "Doing it in a Honda Civic", "A pube in the soup",
  "The morning-after pill", "Nipple tassels", "Getting dumped mid-sex", "A lingering smell of Lynx and regret",
  "Body shots off the vicar", "A leaked nude", "Dirty talk that's just shopping lists", "The Mile High Club toilet queue",
  "A butt plug in airport security", "Screaming the wrong name", "Chafing", "Sexy Santa",
  "A threesome with two Tinder dates", "A hickey the size of a fist", "A strip club loyalty card", "Swinging (the lifestyle, not the playground thing)",
  "An OnlyFans for feet", "Getting off with the best man", "A condom that's been in my wallet since 2014", "An STI test",
  "The sex dungeon under the pub", "My left nut", "A bloke named Big Steve", "The world's most awkward orgasm",
  "Accidentally joining an orgy", "Nudes with the flash on", "A wet patch", "Anal beads from the pound shop",
  "Getting frisky in a tent in the rain", "Crabs", "Hairy palms", "A furious booty call",
  "An inflatable sex doll called Brenda", "Leather chaps", "Porn with a plot", "A one-night stand that became a lease",
  "Dogging in the Asda car park", "A happy ending", "Being too drunk to perform", "A snog that tastes of Doritos",
  "Having sex to Enya", "Sexting with autocorrect", "An unfortunate rash", "Tantric breathing",
  "A lady garden", "A very lucky vicar", "The stripper from the hen do", "Using a banana for practice",
  "Waking up in a stranger's onesie", "Morning breath and bad decisions", "A spanking from a traffic warden", "Crotchless pants",
  "Moaning like a Victorian ghost", "The hot tub at Center Parcs", "Shagging in the Waitrose car park", "Cheeky nudes on the family iPad",
  "The Tinder date who brought his mum", "A willy-shaped cake", "Getting caught by the police in a lay-by", "Twerking in A&E",
  "A suspicious lump", "Sexy time with the lights on", "An enormous ego and a tiny everything else", "Dry humping at a funeral",
  "A really thorough doctor", "Nude yoga", "My fetish for tax returns", "The last condom in Britain",
  "Brazilian waxing gone wrong", "A threesome with two ghosts", "Nipples", "Pulling at a christening",
  "Being bad at sex but great at chatting", "The morning after the Christmas party", "Pleasuring myself to Countryfile", "A dildo in the dishwasher",
  "Drunk-ordering sex toys", "The vicar's secret Tinder", "Getting stuck in the loft with a Tinder date", "Doing it on a trampoline",
  "Accidentally sending a nude to the work group chat", "A saucy lollipop lady", "A love bite from a goose", "Streaking at a village fete",
  "The squelching noise", "An absolutely mortifying bedroom mirror", "Balls deep in regret", "A hen party stripper dressed as a fireman",
  "An erotic novel about a fireman", "Kinky bingo", "Knickers on the chandelier", "Losing my virginity to a Busted song",
  "A 69 that went wrong", "The sex noises coming from the vicarage", "Getting a lap dance from the Landlord", "Tongue piercings",
  "Pulling my back mid-thrust", "The 'lucky pants'", "A very sticky situation", "Accidental exhibitionism",
  "Spit or swallow (mouthwash, obviously)", "Stripping to pay off my student loan", "Topless darts", "My massive tits",
  "A sad little willy", "A sausage that isn't from the full English", "Thrusting like a startled walrus", "Sex on a waterbed",
  "A threesome that turned into a book club", "Waking up with glitter in places", "A bum tattoo of my ex's initials", "The cheapest brothel in Amsterdam",
  "My dad's secret stash", "A spit roast (the barbecue kind, obviously)", "Doing it in the Wetherspoons toilets", "Being the third wheel in a threesome",
  "Crying after sex", "A post-coital cheese toastie", "Sexy role play as HMRC", "The Kama Sutra for beginners",
];

export const HAND_SIZE = 7;
