// Prompt decks for each round type. Add your own in-jokes here!
// {player} is replaced with a random player's name when the game is built.

// ------------------------------------------------------------------ mild

export const MILD = {
  likely: [
    "Who is most likely to text their ex tonight?",
    "Who is most likely to fall asleep at the party?",
    "Who is most likely to get lost on the way home?",
    "Who is most likely to start a fight with a bouncer?",
    "Who is most likely to cry at a film?",
    "Who is most likely to survive a zombie apocalypse?",
    "Who is most likely to order a kebab at 3am?",
    "Who is most likely to get a questionable tattoo on holiday?",
    "Who is most likely to lose their phone tonight?",
    "Who is most likely to end up on a reality TV show?",
    "Who is most likely to befriend a stranger in the toilets?",
    "Who is most likely to reply-all by accident?",
    "Who is most likely to cheat at Monopoly?",
    "Who is most likely to say 'one more drink' and mean fifteen?",
    "Who is most likely to join a cult by accident?",
    "Who is most likely to get married in Vegas?",
    "Who is most likely to be arrested for something ridiculous?",
    "Who is most likely to have the worst search history?",
  ],
  nhie: [
    "Never have I ever sent a text to the wrong person.",
    "Never have I ever pretended to be ill to skip work.",
    "Never have I ever fallen asleep on public transport and missed my stop.",
    "Never have I ever been kicked out of a bar.",
    "Never have I ever stalked an ex on social media.",
    "Never have I ever re-gifted a present.",
    "Never have I ever ghosted someone.",
    "Never have I ever broken something and blamed someone else.",
    "Never have I ever walked into a glass door.",
    "Never have I ever drunk-ordered something online.",
    "Never have I ever lost a shoe on a night out.",
    "Never have I ever faked a phone call to escape a conversation.",
    "Never have I ever read someone else's messages without them knowing.",
  ],
  wyr: [
    ["Always be 10 minutes late", "Always be 20 minutes early"],
    ["Only drink warm beer forever", "Only drink flat fizzy drinks forever"],
    ["Fight one horse-sized duck", "Fight 100 duck-sized horses"],
    ["Have hiccups for the rest of your life", "Always feel like you're about to sneeze"],
    ["Have your search history made public", "Have your texts made public"],
    ["Sing everything you say", "Dance everywhere you walk"],
    ["Be stuck in a lift with your boss", "Be stuck in a lift with your ex"],
    ["Wake up at 5am every day", "Go to bed at 5am every day"],
  ],
  quip: [
    "The worst thing to hear from your pilot: \"___\"",
    "A terrible name for a pub: ___",
    "The real reason the dinosaurs died out: ___",
    "A bad thing to shout at a wedding: \"___\"",
    "Rejected slogan for a dating app: \"___\"",
    "What you should never say to a bouncer: \"___\"",
    "The worst thing to find in your hotel bed: ___",
    "What the group chat is really called: ___",
    "{player}'s autobiography title: ___",
    "What your dog is actually thinking: \"___\"",
    "The worst possible first line of a best-man speech: \"___\"",
    "The worst thing to hear from the next toilet cubicle: \"___\"",
  ],
  social: [
    "Everyone wearing black drinks!",
    "The last person to touch their nose drinks. GO!",
    "Waterfall! Everyone drinks until the person on the host's left stops.",
    "Youngest player drinks 2 sips.",
    "Oldest player hands out 3 sips.",
    "Anyone with a phone battery under 30% drinks.",
    "Thumb master: the last person to put their thumb on the table drinks.",
    "Everyone swaps seats. The last to sit down drinks.",
  ],
};

// ------------------------------------------------------------------ filthy

export const FILTHY = {
  likely: [
    "Who is most likely to have slept with someone at a wedding?",
    "Who is most likely to have a secret OnlyFans?",
    "Who is most likely to get off with a stranger tonight?",
    "Who is most likely to have faked it?",
    "Who is most likely to send nudes to the wrong person?",
    "Who is most likely to shag their boss?",
    "Who is most likely to wake up somewhere they don't recognise?",
    "Who is most likely to cry after sex?",
    "Who is most likely to have been walked in on?",
    "Who is most likely to be the worst in bed?",
    "Who is most likely to marry for money?",
    "Who is most likely to die in a really stupid way?",
    "Who is most likely to vomit tonight?",
    "Who is most likely to have hooked up with someone in this room?",
    "Who is most likely to get divorced first?",
    "Who is most likely to sell out their friends for a tenner?",
    "Who is most likely to have the weirdest kink?",
    "Who is most likely to end up on a true-crime documentary?",
    "Who is most likely to have been banned from a pub?",
    "Who is most likely to ghost someone after sleeping with them?",
    "Who has the worst taste in partners?",
    "Who would be the first to eat the others after a plane crash?",
    "Who is most likely to still be drunk at work on Monday?",
    "Who is most likely to have slept with an ex's mate?",
  ],
  nhie: [
    "Never have I ever had sex in a public place.",
    "Never have I ever sent a nude.",
    "Never have I ever faked an orgasm.",
    "Never have I ever hooked up with someone whose name I didn't know.",
    "Never have I ever been caught having sex.",
    "Never have I ever slept with a friend's ex.",
    "Never have I ever had a one-night stand.",
    "Never have I ever peed in a swimming pool.",
    "Never have I ever thrown up in a taxi.",
    "Never have I ever cheated on someone.",
    "Never have I ever been so drunk I lost an entire night.",
    "Never have I ever had sex at work.",
    "Never have I ever kissed someone in this room.",
    "Never have I ever lied about how many people I've slept with.",
    "Never have I ever woken up next to someone and instantly regretted it.",
    "Never have I ever used a sex toy.",
    "Never have I ever had a crush on someone in this room.",
    "Never have I ever shat myself as an adult.",
    "Never have I ever been sick on another person.",
    "Never have I ever gone skinny dipping.",
    "Never have I ever had a sex dream about a friend.",
    "Never have I ever done the walk of shame.",
    "Never have I ever slid into someone's DMs at 3am.",
  ],
  wyr: [
    ["Have sex with the lights on forever", "Never have sex with the lights on again"],
    ["Have your parents watch your sex tape", "Watch your parents' sex tape"],
    ["Sleep with your ex", "Sleep with your boss"],
    ["Have everyone here know your body count", "Have everyone here read your texts"],
    ["Shit yourself on a first date", "Throw up on your wedding day"],
    ["Get caught wanking by your mum", "Catch your mum at it"],
    ["Lick a pub toilet seat", "Drink a pint of a stranger's sweat"],
    ["Never drink alcohol again", "Never have sex again"],
    ["Have your partner read your search history", "Have your boss read your search history"],
    ["Fart loudly during sex", "Sneeze into someone's mouth during a first kiss"],
    ["Date someone who's great in bed but boring", "Date someone hilarious but awful in bed"],
    ["Go to prison for 5 years", "Live with your parents for 10"],
    ["Let the group post anything on your Instagram", "Let the group send one text from your phone"],
    ["Know what everyone here really thinks of you", "Have everyone here know what you think of them"],
    ["Have a permanent hangover", "Be permanently a little bit drunk"],
    ["Get caught having sex by the police", "Get caught having sex by your nan"],
  ],
  quip: [
    "The worst thing to moan during sex: \"___\"",
    "{player}'s browser history is 90% ___",
    "What {player} is really doing when they 'work from home': ___",
    "The worst thing to find in your partner's bedside drawer: ___",
    "A terrible safe word: \"___\"",
    "What {player} will eventually be arrested for: ___",
    "The least sexy thing to whisper in someone's ear: \"___\"",
    "{player}'s Tinder bio, if it was honest: \"___\"",
    "The worst thing to say in a funeral eulogy: \"___\"",
    "The real reason {player} is still single: ___",
    "The title of {player}'s sex tape: ___",
    "A rejected flavour of condom: ___",
    "The worst thing to hear the morning after: \"___\"",
    "What really happened at {player}'s last work Christmas party: ___",
    "A terrible thing to text your mum by accident: \"___\"",
    "The worst possible lower-back tattoo: ___",
    "What the doctor actually found up there: ___",
    "A dating app exclusively for people into ___",
    "The worst thing to shout as you finish: \"___\"",
    "The worst thing to find out on a first date: ___",
    "The real reason the stag do got cancelled: ___",
    "Something {player} would do for £50: ___",
    "A porn parody of a kids' film: ___",
    "The one thing you never do in a hot tub: ___",
    "What {player}'s ex says about them: \"___\"",
    "The worst thing to say to a police officer when you're hammered: \"___\"",
    "A terrible name for a sex toy: ___",
    "{player}'s last words: \"___\"",
  ],
  social: [
    "Everyone who's had sex in the last week drinks.",
    "Whoever had the most recent one-night stand drinks 3. Details are optional. They're not.",
    "On three, point at the person most likely to die alone. Most pointed-at drinks.",
    "Everyone who still has an ex's number saved drinks.",
    "Honesty shot: say your body count out loud or drink 3.",
    "Everyone who's been sick on a night out this year drinks.",
    "Hot seat: the host picks a victim. Everyone asks them one question. Every refusal is a drink.",
    "Anyone who has sent a risky text tonight drinks. Show the group or drink double.",
    "Anyone who's kissed someone in this room drinks. Both of you.",
  ],
};

// ------------------------------------------------------------------ Lie Detector

// Weird-but-true facts. Players invent fake answers to fool each other.
export const FIBS = [
  { q: "Wombat poo is shaped like ___.", a: "cubes" },
  { q: "A group of flamingos is called a ___.", a: "flamboyance" },
  { q: "The national animal of Scotland is the ___.", a: "unicorn" },
  { q: "Octopuses have ___ hearts.", a: "three" },
  { q: "In 1932 the Australian army went to war against ___, and lost.", a: "emus" },
  { q: "The man who designed the Pringles tube had some of his ashes buried in ___.", a: "a Pringles tube" },
  { q: "The first product ever scanned with a barcode was a pack of ___.", a: "chewing gum" },
  { q: "The dot over a lowercase 'i' is called a ___.", a: "tittle" },
  { q: "The world's first webcam was set up to watch a ___.", a: "coffee pot" },
  { q: "In the 1830s ketchup was sold as a ___.", a: "medicine" },
  { q: "Napoleon was once attacked by a horde of ___.", a: "rabbits" },
  { q: "Queen Elizabeth II trained during WW2 as a ___.", a: "mechanic" },
  { q: "The Hawaiian pizza was invented in ___.", a: "Canada" },
  { q: "Pigeons have been trained to tell the difference between paintings by Picasso and ___.", a: "Monet" },
  { q: "Sea otters hold ___ while they sleep so they don't drift apart.", a: "hands" },
  { q: "In seahorses, it's the males that ___.", a: "give birth" },
  { q: "Scots has over 400 words for ___.", a: "snow" },
  { q: "Honey found in ancient Egyptian tombs was still ___.", a: "edible" },
  { q: "Bananas are slightly ___.", a: "radioactive" },
  { q: "A group of crows is called a ___.", a: "murder" },
];

// ------------------------------------------------------------------ host lines

// What The Landlord says. {name}, {winner}, {liar}, {thirsty}, {last} and {other} are
// filled with player names; a line is only used when all of its blanks can be filled.
export const LINES = {
  welcome: [
    "Welcome to Last Orders. I'm the Landlord. Tonight you'll drink, you'll lie, and you'll find out what your friends really think of you.",
    "Evening. I see {name} made it. Brave. Given everything.",
    "Welcome, welcome. {name}, {other}, lovely to see you. Well. To see you.",
    "Right, you lot. Phones out, standards down. {name}, you've done that already. Good.",
    "Welcome to Last Orders. The rules are simple: answer honestly, drink when told, and don't make eye contact with {name}.",
  ],
  likely: [
    "{name}. The group has spoken, and frankly, the group is right.",
    "{name}, it wasn't even close. Your friends have known this about you for years.",
    "Congratulations {name}. Unanimous-ish. Drink, and have a little think about your life.",
    "{name}. Nobody was surprised. Least of all {name}.",
  ],
  nhie: [
    "{name}, drink. And we'll be discussing that later.",
    "Look at {name}, drinking. Not even a flicker of shame. Impressive.",
    "{name} has. Of course {name} has.",
    "Honesty is a virtue, {name}. Unfortunately so is not doing that in the first place.",
  ],
  nhie_none: [
    "Nobody? Nobody at all? Right. I'll just assume you're all liars and move on.",
    "Not one of you. A room full of saints. Or cowards. Mostly cowards.",
  ],
  wyr: [
    "{name}, you picked that. Out loud. In front of people. Drink.",
    "Interesting choice, {name}. Wrong, but interesting.",
    "{name} is in the minority, which is a lovely way of saying everyone thinks you're weird.",
  ],
  wyr_tie: [
    "A perfect split. You're all as bad as each other. Everybody drinks.",
  ],
  quip: [
    "{winner} takes it. Genuinely funny. I'm as shocked as you are.",
    "The crowd loves {winner}. The crowd has also been drinking, so let's not get carried away.",
    "{name}, not a single vote. Not even a pity vote. Drink up.",
    "{name}, zero votes. Your answer was so bad even you didn't vote for it. You couldn't, but still.",
  ],
  fib: [
    "{name}, you got fooled by {liar}. Which, if we're honest, isn't the first time someone's lied to you tonight.",
    "{liar} lied, and {name} swallowed it. Story of {name}'s love life.",
    "Beautiful lying from {liar}. Should be in politics. Or prison. Often both.",
    "{name} fell for it. Drink, and never buy a used car.",
  ],
  drink: [
    "{name}, drink. You know what you did.",
    "{name}, get it down you. Your liver's seen worse. Mostly from you.",
    "Drink up, {name}. It won't make you any funnier, but it'll make everyone else seem funnier.",
    "{name}. Drink. Don't make me say it twice. Actually I will, it's the only fun I get. Drink.",
  ],
  none: [
    "Nobody drinks? That's not a drinking game, that's a book club.",
    "Well. That's going in the group chat.",
    "Remarkable. Not good. Just remarkable.",
  ],
  final: [
    "That's the game. {winner} wins. Enjoy it, {winner}, it's the most anyone's ever rated you. {thirsty} drank the most, and {last} came last, which feels about right.",
    "Your winner is {winner}. Take a bow. Not too low, you'll fall over. {thirsty}, you drank the most. Have some water. And maybe a word with yourself.",
    "{winner} wins. {last} loses. {thirsty} is drunk. Same time next week?",
  ],
};

export const ROUND_INFO = {
  likely: { title: "Most Likely To", emoji: "👉", rules: "Vote for the friend who fits best. Most-voted drinks 2. Vote with the crowd for 100 points." },
  nhie: { title: "Never Have I Ever", emoji: "🙊", rules: "Be honest! If you have, drink 1 — but get 50 points for confessing." },
  wyr: { title: "Would You Rather", emoji: "⚖️", rules: "Pick a side. The minority drinks 1, the majority scores 100." },
  quip: { title: "Quip Clash", emoji: "✍️", rules: "Write the funniest answer, then vote. 100 points per vote. Zero votes? Drink 2." },
  fib: { title: "Lie Detector", emoji: "🤥", rules: "Write a fake answer to fool everyone, then find the truth. Truth = 200 pts. Fooled = drink 1. Every sucker you fool = 100 pts." },
  social: { title: "Social", emoji: "🍻", rules: "Everybody follow the rule on screen!" },
};

export function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
