// Extra prompt packs, merged into the decks in prompts.js. Add your own here too.
// Facts (Lie Detector, Year Guess, Pub Quiz) are meant to be true: double-check before adding.

export const EXTRA = {
  mild: {
    likely: [
      "Who is most likely to win the lottery and lose the ticket?",
      "Who is most likely to become a meme?",
      "Who is most likely to sleep through their own wedding?",
      "Who is most likely to adopt a pet without telling their partner?",
      "Who is most likely to get into an argument with a self-checkout?",
      "Who is most likely to be recognised by the staff at their local takeaway?",
      "Who is most likely to cry at an advert?",
      "Who is most likely to accidentally join a flash mob?",
      "Who is most likely to have a secret TikTok following?",
      "Who is most likely to be late to their own funeral?",
      "Who is most likely to go viral for the wrong reasons?",
      "Who is most likely to befriend a seagull?",
      "Who is most likely to bring Tupperware to a buffet?",
      "Who is most likely to try to fight a goose?",
      "Who is most likely to fall asleep in the cinema?",
      "Who is most likely to become a conspiracy theorist?",
      "Who is most likely to live to 100?",
      "Who is most likely to be first out in a zombie film?",
      "Who is most likely to leave a party without saying goodbye?",
      "Who is most likely to argue with a referee from the sofa?",
      "Who is most likely to lie on their CV?",
      "Who is most likely to get stuck in a lift?",
      "Who is most likely to go on a reality dating show?",
      "Who is most likely to set off a fire alarm while cooking?",
      "Who is most likely to get lost in IKEA?",
      "Who is most likely to name their kid after a footballer?",
      "Who is most likely to take a selfie at a funeral?",
      "Who is most likely to still have a Nokia in a drawer?",
      "Who is most likely to eat something off the floor at a party?",
      "Who is most likely to become a vicar?",
      "Who is most likely to know every word to a musical?",
      "Who is most likely to fall for a scam email?",
      "Who is most likely to be banned from a Wetherspoons?",
      "Who is most likely to pretend they've seen a film they haven't?",
      "Who is most likely to become an influencer?",
      "Who is most likely to buy a boat on a whim?",
      "Who is most likely to sing karaoke sober?",
      "Who is most likely to get a tattoo of someone's name?",
      "Who is most likely to fake an accent for a whole holiday?",
      "Who is most likely to cry when their team loses?",
    ],
    nhie: [
      "Never have I ever fallen asleep in a meeting.",
      "Never have I ever pretended to be on the phone to avoid someone.",
      "Never have I ever lied about my height.",
      "Never have I ever eaten a whole pizza by myself.",
      "Never have I ever cried at a TV advert.",
      "Never have I ever been to a festival and not seen a single band.",
      "Never have I ever sent a screenshot to the person it was about.",
      "Never have I ever faked being sick to get out of plans.",
      "Never have I ever accidentally liked an old photo while stalking someone.",
      "Never have I ever lost my keys on a night out.",
      "Never have I ever cut in a queue on purpose.",
      "Never have I ever been told off by a teacher for laughing.",
      "Never have I ever pretended to know a celebrity.",
      "Never have I ever driven the wrong way down a one-way street.",
      "Never have I ever fallen over on a night out.",
      "Never have I ever gone a week without washing my hair.",
      "Never have I ever lied to get out of a work drinks.",
      "Never have I ever eaten something past its use-by date on purpose.",
      "Never have I ever forgotten a friend's birthday.",
      "Never have I ever been sick at a theme park.",
      "Never have I ever cried because I was hungry.",
      "Never have I ever pretended my phone had died.",
      "Never have I ever stolen a glass from a pub.",
      "Never have I ever blamed a fart on someone else.",
      "Never have I ever been banned from a shop.",
      "Never have I ever ordered a takeaway to avoid going to an event.",
      "Never have I ever sung in a public toilet.",
      "Never have I ever read the last page of a book first.",
      "Never have I ever lied in a job interview.",
      "Never have I ever fallen asleep on a night out while still out.",
      "Never have I ever talked to my pet like it's a person.",
      "Never have I ever had a crush on a cartoon character.",
      "Never have I ever woken up still drunk.",
      "Never have I ever been locked out of my own house.",
      "Never have I ever cheated at a board game.",
    ],
    wyr: [
      ["Only eat cereal for every meal", "Never eat cereal again"],
      ["Always have to sing instead of speaking", "Always have to dance instead of walking"],
      ["Be famous for something embarrassing", "Never be famous at all"],
      ["Live without the internet", "Live without heating"],
      ["Have a rewind button", "Have a pause button"],
      ["Always say what you're thinking", "Never speak again"],
      ["Be able to talk to animals", "Speak every language"],
      ["Have unlimited free pints", "Have unlimited free takeaways"],
      ["Be stuck on a desert island alone", "Be stuck with someone who never stops talking"],
      ["Only wear flip-flops forever", "Only wear wellies forever"],
      ["Have your mum as your boss", "Have your boss as your mum"],
      ["Always be slightly too hot", "Always be slightly too cold"],
      ["Know all the gossip in town", "Be the gossip in town"],
      ["Relive the same day for a year", "Lose a year of your life"],
      ["Have a personal theme tune that plays when you walk in", "Have a laugh track that plays after everything you say"],
      ["Give up crisps", "Give up chocolate"],
      ["Only listen to one song forever", "Never listen to music again"],
      ["Be the funniest person in every room", "Be the best-looking person in every room"],
      ["Win £1 million today", "Win £5,000 a month for life"],
      ["Be a famous popstar with no privacy", "Be rich and completely unknown"],
      ["Travel back to the 1980s", "Travel forward to 2080"],
      ["Always have wet socks", "Always have a stone in your shoe"],
      ["Never use your phone again", "Never watch TV again"],
      ["Have fingers as long as your legs", "Have legs as long as your fingers"],
      ["Only be able to whisper", "Only be able to shout"],
      ["Have a bottomless pint", "Have a never-ending bag of chips"],
      ["Be invisible", "Be able to fly"],
      ["Lose your sense of taste", "Lose your sense of smell"],
      ["Never have to sleep", "Never have to eat"],
      ["Go on holiday with your parents", "Go on holiday with your boss"],
    ],
    quip: [
      "The worst thing to hear your dentist say: \"___\"",
      "A rejected name for a new chocolate bar: ___",
      "What the Loch Ness Monster actually is: ___",
      "The worst excuse for being late to your own wedding: \"___\"",
      "A new Olympic sport the UK would finally win: ___",
      "The most British way to die: ___",
      "What's really at the end of the rainbow: ___",
      "A terrible slogan for a budget airline: \"___\"",
      "The worst superpower to get on a night out: ___",
      "What cats are actually plotting: ___",
      "A terrible name for a boat: ___",
      "The worst thing to say on a first date: \"___\"",
      "What your nan's WhatsApp group is really about: ___",
      "The worst possible flavour of vape: ___",
      "A rubbish name for a band: ___",
      "What you'd find in the Queen Vic's cellar: ___",
      "The one item you shouldn't take through airport security: ___",
      "The real reason Stonehenge was built: ___",
      "A terrible theme for a kid's birthday party: ___",
      "The worst thing to hear on the plane's speakers: \"___\"",
      "A terrible name for a hairdresser's: ___",
      "What the pigeons are saying about us: \"___\"",
      "The most useless thing to bring on Bear Grylls' island: ___",
      "The next big TikTok trend: ___",
      "A terrible reason to call 999: \"___\"",
      "What really happens at the office Christmas party: ___",
      "The worst thing to find in a Kinder Egg: ___",
      "A bad name for a racehorse: ___",
      "The worst thing to write on a Valentine's card: \"___\"",
      "The least relaxing spa treatment: ___",
      "What {player} would bring to a desert island: ___",
      "{player}'s secret talent: ___",
      "What {player} would be famous for: ___",
      "The worst advice {player} has ever given: \"___\"",
      "{player}'s specialist subject on Mastermind: ___",
      "The name of {player}'s future autobiography: ___",
      "What {player} is thinking right now: \"___\"",
      "{player}'s last Google search: ___",
      "The worst thing to hear your Uber driver say: \"___\"",
      "A new flavour of Pot Noodle: ___",
      "What Santa does for the rest of the year: ___",
      "A terrible name for a care home: ___",
      "The Ten Commandments' lost 11th rule: ___",
      "The worst thing to say to the King: \"___\"",
      "The one thing you shouldn't microwave: ___",
      "A rejected Bond film title: ___",
      "The worst motivational poster slogan: \"___\"",
      "What the Tooth Fairy does with all the teeth: ___",
      "A terrible fact to learn about your new flatmate: ___",
      "The real reason the dinosaurs couldn't get a mortgage: ___",
    ],
    social: [
      "Everyone who's been to Ibiza drinks.",
      "The person with the oldest phone drinks.",
      "Anyone who's been on a plane this year drinks.",
      "Everyone with a tattoo drinks. Two if you regret it.",
      "The person who's had the longest relationship drinks.",
      "Last person to raise their hand drinks. GO!",
      "Anyone who's met a celebrity drinks — prove it or drink double.",
      "The person who lives furthest away drinks.",
      "Everyone who's ever been on a stag or hen do drinks.",
      "Categories: things you find in a pub. First to hesitate drinks.",
      "Everyone who's been to a wedding this year drinks.",
      "Anyone with siblings drinks once per sibling.",
      "The person who most recently cried drinks.",
      "Anyone wearing trainers drinks.",
      "Point at the person most likely to be drunk first. Most pointed-at drinks.",
      "Never-ending rhyme: the host says a word, go round. First to fail drinks.",
      "Everyone who's ever been sick on a boat drinks.",
      "Whoever arrived last tonight drinks.",
      "Everyone must speak in an accent until the next round. Slip up and drink.",
      "Everyone who's been single on Valentine's Day drinks.",
      "The person with the most apps on their phone drinks.",
      "Anyone who's ever broken a bone drinks.",
      "The youngest and oldest players drink together.",
      "Everyone who can't whistle drinks. Prove it.",
    ],
  },

  filthy: {
    likely: [
      "Who is most likely to have had sex in a car?",
      "Who is most likely to have a sex dream about someone here?",
      "Who is most likely to have slept with their boss?",
      "Who is most likely to get caught with their pants down?",
      "Who is most likely to have a secret second phone?",
      "Who is most likely to have been chucked out of a club for being too drunk?",
      "Who is most likely to have been sick in their own handbag?",
      "Who is most likely to send a nude to the family WhatsApp?",
      "Who is most likely to join the mile-high club?",
      "Who is most likely to marry someone they met that night?",
      "Who is most likely to wet themselves laughing?",
      "Who is most likely to have a filthy search history?",
      "Who is most likely to have slept with someone famous?",
      "Who is most likely to get arrested on holiday?",
      "Who is most likely to cheat at a pub quiz?",
      "Who is most likely to wake up next to a stranger tomorrow?",
      "Who is most likely to fake their own death to get out of a relationship?",
      "Who is most likely to have a naughty nickname?",
      "Who is most likely to get off with someone at a funeral?",
      "Who is most likely to end up on a hidden-camera show?",
      "Who is most likely to have done a walk of shame this year?",
      "Who is most likely to have sexted the wrong person?",
      "Who is most likely to have the most exes?",
      "Who is most likely to cry during sex?",
      "Who is most likely to have been in a threesome?",
      "Who is most likely to steal someone's partner?",
      "Who is most likely to pass out first tonight?",
      "Who is most likely to have the longest list of regrets?",
      "Who is most likely to have a secret kink nobody would guess?",
      "Who is most likely to snog someone in this room tonight?",
      "Who is most likely to sleep with an ex after this game?",
      "Who is most likely to get a sexually transmitted anything?",
      "Who is most likely to get their nipples pierced on a whim?",
      "Who is most likely to fall asleep on the toilet?",
      "Who is most likely to have lied about their body count?",
      "Who is most likely to cry at a strip club?",
    ],
    nhie: [
      "Never have I ever had sex in a car.",
      "Never have I ever been in a threesome.",
      "Never have I ever had sex on a beach.",
      "Never have I ever joined the mile-high club.",
      "Never have I ever hooked up with a colleague.",
      "Never have I ever had sex in my parents' house.",
      "Never have I ever been walked in on.",
      "Never have I ever sexted someone I'd never met.",
      "Never have I ever slept with someone on the first date.",
      "Never have I ever had a friends-with-benefits.",
      "Never have I ever slept with someone to get back at an ex.",
      "Never have I ever had sex in a tent.",
      "Never have I ever been to a strip club.",
      "Never have I ever flashed someone.",
      "Never have I ever hooked up with two people in one night.",
      "Never have I ever gone home with someone I met in a queue.",
      "Never have I ever woken up not knowing where I was.",
      "Never have I ever been sick during a snog.",
      "Never have I ever fallen asleep during sex.",
      "Never have I ever lied about being single.",
      "Never have I ever had sex in a toilet.",
      "Never have I ever sent a nude and immediately regretted it.",
      "Never have I ever slept with an ex's sibling.",
      "Never have I ever called someone the wrong name in bed.",
      "Never have I ever hooked up at a wedding.",
      "Never have I ever had a one-night stand abroad.",
      "Never have I ever used food in the bedroom.",
      "Never have I ever been caught watching porn.",
      "Never have I ever had a crush on a friend's parent.",
      "Never have I ever got with someone I met on a night out and never saw again.",
      "Never have I ever peed in public.",
      "Never have I ever lost my underwear on a night out.",
      "Never have I ever faked being drunker than I was.",
      "Never have I ever gone skinny dipping with people I'd just met.",
      "Never have I ever had sex outdoors.",
    ],
    wyr: [
      ["Have sex with no foreplay", "Have foreplay but no sex"],
      ["Everyone sees your browser history", "Everyone reads your DMs"],
      ["Sleep with a celebrity and nobody believes you", "Everyone thinks you did and you didn't"],
      ["Have your ex as your boss", "Have your boss as your ex"],
      ["Only have sex in the dark", "Only have sex with the lights on"],
      ["Have a threesome with two exes", "Never have sex again with anyone new"],
      ["Get caught by your parents", "Catch your parents"],
      ["Moan like a donkey", "Scream like a banshee every time"],
      ["Date someone who snores like a chainsaw", "Date someone who farts in their sleep"],
      ["Have your first kiss filmed and shown at your wedding", "Have your worst date filmed and shown at your wedding"],
      ["Let your partner read your texts", "Let your partner read your search history"],
      ["Sleep with the best-looking person you know once", "Sleep with the funniest person you know for a year"],
      ["Have your sex life narrated by David Attenborough", "Have it commentated by a football pundit"],
      ["Lick a stranger's armpit", "Drink a stranger's bathwater"],
      ["Kiss the ugliest person you know", "Kiss your worst enemy"],
      ["Only be able to have sex on a train", "Only be able to have sex in a tent"],
      ["Sneeze every time you orgasm", "Orgasm every time you sneeze"],
      ["Be caught by the police doing it", "Be caught by your boss doing it"],
      ["Have a partner who's amazing in bed but never showers", "Have a partner who's terrible in bed but always smells amazing"],
      ["Show your nudes to your nan", "Show your search history to your dad"],
      ["Wet yourself in a meeting", "Throw up at a funeral"],
      ["Get a tattoo of your ex's name", "Get a tattoo of your ex's face"],
      ["Never drink again", "Only drink with your parents"],
      ["Go on a date with your ex's new partner", "Go on a date with your partner's ex"],
      ["Have a one-night stand with a stranger", "Have a one-night stand with a friend"],
    ],
    quip: [
      "The worst thing to hear during sex: \"___\"",
      "What {player} shouts in bed: \"___\"",
      "The name of {player}'s OnlyFans: ___",
      "{player}'s worst sexual experience involved ___",
      "The real reason {player} got dumped: ___",
      "What {player}'s ex told the group chat: \"___\"",
      "The worst pick-up line: \"___\"",
      "What {player} keeps in their bedside drawer: ___",
      "The worst thing to find in a hotel room drawer: ___",
      "A terrible name for a strip club: ___",
      "What {player}'s tattoo really says: ___",
      "The worst thing to say after sex: \"___\"",
      "The title of the porno based on this group: ___",
      "What {player} does alone on a Friday night: ___",
      "A rejected Ann Summers product: ___",
      "The worst thing to accidentally send to your boss: ___",
      "What happened at {player}'s last one-night stand: ___",
      "A terrible theme for a swingers' party: ___",
      "The worst excuse for being caught naked in a garden: \"___\"",
      "What {player} whispers to themselves in the mirror: \"___\"",
      "The one thing you never say at a sex shop till: \"___\"",
      "The weirdest thing {player} has done drunk: ___",
      "What really happened on {player}'s stag/hen do: ___",
      "The worst name for a dating app: ___",
      "{player}'s search history, in three words: ___",
      "The worst thing to hear from your doctor after a check-up down there: \"___\"",
      "The least sexy lingerie: ___",
      "What {player}'s mum would say if she saw their browser history: \"___\"",
      "The worst smell in a hotel room: ___",
      "What really goes on in the Love Island hideaway: ___",
      "A terrible safe word for a first date: \"___\"",
      "The real reason {player} is always tired: ___",
      "{player}'s porn star name: ___",
      "The worst thing to hear in a hot tub: \"___\"",
      "What the barman thinks of {player}: \"___\"",
      "The worst advert for condoms: \"___\"",
      "What {player} got up to in the toilets: ___",
      "The world's worst sex tip: \"___\"",
      "A rejected flavour of lube: ___",
      "{player}'s dating profile photo is ___",
    ],
    social: [
      "Anyone who's had a one-night stand this year drinks.",
      "Everyone point to who'd be worst in bed. Most pointed-at drinks 2.",
      "Anyone who's slept with someone in this room drinks. No, you don't have to say who. Yet.",
      "The last person to have kissed someone drinks.",
      "Everyone who's been caught in the act drinks twice.",
      "Anyone who has a secret they'd never tell this group drinks.",
      "Show the last photo in your camera roll or drink 3.",
      "Read out your last text or drink 3.",
      "Anyone who's ever sent a nude drinks. Sent one this week? Finish your drink.",
      "Everyone who's gone home with someone from a club drinks.",
      "Whoever has the most exes drinks one per ex. Keep count out loud.",
      "Anyone who's been sick on a night out this month drinks.",
      "Truth or drink: the host asks the person on their left anything.",
      "Everyone who's ever cheated at anything drinks. Liars drink double.",
    ],
  },

  fib: [
    { q: "The shortest war in history, between Britain and Zanzibar, lasted about ___.", a: "38 minutes" },
    { q: "A day on Venus is longer than a ___ on Venus.", a: "year" },
    { q: "Cleopatra lived closer in time to the Moon landing than to the building of the ___.", a: "Great Pyramid" },
    { q: "The man who invented the modern frisbee had his ashes made into ___.", a: "frisbees" },
    { q: "Oxford University is older than the ___ Empire.", a: "Aztec" },
    { q: "A group of owls is called a ___.", a: "parliament" },
    { q: "A group of ferrets is called a ___.", a: "business" },
    { q: "Nintendo started out in 1889 making ___.", a: "playing cards" },
    { q: "Google's original name was ___.", a: "BackRub" },
    { q: "Pepsi was originally called ___.", a: "Brad's Drink" },
    { q: "In Switzerland it's illegal to own just one ___.", a: "guinea pig" },
    { q: "Humans and giraffes have the same number of ___ in their necks.", a: "vertebrae" },
    { q: "A shrimp's heart is in its ___.", a: "head" },
    { q: "The Eiffel Tower was originally meant to be taken down after ___ years.", a: "20" },
    { q: "Lobster was once so cheap and unloved in America that it was fed to ___.", a: "prisoners" },
    { q: "Bubble wrap was originally invented to be sold as ___.", a: "wallpaper" },
    { q: "Play-Doh was originally sold as ___.", a: "wallpaper cleaner" },
    { q: "The material in Kleenex tissues was first used in World War One as filters for ___.", a: "gas masks" },
    { q: "Coca-Cola was first sold in a ___.", a: "pharmacy" },
    { q: "Mr Potato Head was the first toy ever advertised on ___.", a: "television" },
    { q: "There are more possible games of chess than there are ___ in the observable universe.", a: "atoms" },
    { q: "The Great Fire of London started in a ___.", a: "bakery" },
    { q: "One of Henry VIII's servants had the job title 'Groom of the ___'.", a: "Stool" },
    { q: "Ancient Romans used ___ as mouthwash.", a: "urine" },
    { q: "Bees can recognise human ___.", a: "faces" },
    { q: "An octopus has ___ blood.", a: "blue" },
    { q: "Scotland has the highest proportion of ___-haired people in the world.", a: "red" },
    { q: "The woman who invented the chocolate chip cookie reportedly sold the recipe to Nestlé for ___.", a: "a lifetime supply of chocolate" },
    { q: "A pineapple plant takes about ___ to grow one pineapple.", a: "two years" },
    { q: "The oldest animal ever found was a clam that lived to ___ years old.", a: "507" },
    { q: "Hot water sometimes freezing faster than cold water is called the ___ effect.", a: "Mpemba" },
    { q: "The first mechanical alarm clock in America could only ring at ___.", a: "4am" },
    { q: "The first item ever sold on eBay was a broken ___.", a: "laser pointer" },
    { q: "Twitter's original name was ___.", a: "twttr" },
    { q: "A group of pugs is called a ___.", a: "grumble" },
    { q: "The # symbol's proper name is the ___.", a: "octothorpe" },
    { q: "The first person ever convicted of speeding in Britain was doing ___ mph.", a: "8" },
    { q: "In 2006 an Australian man tried to sell New Zealand on ___.", a: "eBay" },
    { q: "Ancient Egyptians shaved off their ___ to mourn the death of a cat.", a: "eyebrows" },
    { q: "Astronauts struggle to ___ in space because there's no gravity to separate gas from food.", a: "burp" },
    { q: "Nutella was invented in Italy after WW2 because of a shortage of ___.", a: "cocoa" },
    { q: "Ernő Rubik, who invented the Rubik's Cube, was a professor of ___.", a: "architecture" },
    { q: "The oldest known written recipe is for ___.", a: "beer" },
    { q: "Carrots were originally ___, not orange.", a: "purple" },
    { q: "A jiffy is an actual unit of ___.", a: "time" },
    { q: "Venus spins the opposite way to most planets, so there the Sun rises in the ___.", a: "west" },
    { q: "Strawberries aren't technically berries, but ___ are.", a: "bananas" },
    { q: "A cow-bison hybrid is called a ___.", a: "beefalo" },
    { q: "The inventor of the World Wide Web is Sir Tim ___.", a: "Berners-Lee" },
  ],

  years: [
    { q: "World War One began.", year: 1914 },
    { q: "World War Two ended.", year: 1945 },
    { q: "The NHS was founded.", year: 1948 },
    { q: "The first series of Big Brother aired in the UK.", year: 2000 },
    { q: "Friends first aired.", year: 1994 },
    { q: "The Great British Bake Off first aired.", year: 2010 },
    { q: "The first Wimbledon Championships were held.", year: 1877 },
    { q: "The first FA Cup final was played.", year: 1872 },
    { q: "The Premier League kicked off.", year: 1992 },
    { q: "London hosted the Olympics (the most recent time).", year: 2012 },
    { q: "The film Titanic was released.", year: 1997 },
    { q: "The first Harry Potter film was released.", year: 2001 },
    { q: "Charles and Diana got married.", year: 1981 },
    { q: "Prince William married Kate Middleton.", year: 2011 },
    { q: "Freddie Mercury died.", year: 1991 },
    { q: "Elvis Presley died.", year: 1977 },
    { q: "John Lennon was shot.", year: 1980 },
    { q: "Michael Jackson released 'Thriller'.", year: 1982 },
    { q: "Oasis released 'Definitely Maybe'.", year: 1994 },
    { q: "Live Aid took place.", year: 1985 },
    { q: "Band Aid released 'Do They Know It's Christmas?'.", year: 1984 },
    { q: "The first iPod went on sale.", year: 2001 },
    { q: "Google was founded.", year: 1998 },
    { q: "Amazon was founded.", year: 1994 },
    { q: "Instagram launched.", year: 2010 },
    { q: "WhatsApp launched.", year: 2009 },
    { q: "Spotify launched.", year: 2008 },
    { q: "The first Pokémon games came out in Japan.", year: 1996 },
    { q: "The first ever text message was sent.", year: 1992 },
    { q: "Dolly the sheep, the first cloned mammal, was born.", year: 1996 },
    { q: "Concorde made its last commercial flight.", year: 2003 },
    { q: "Channel 4 launched.", year: 1982 },
    { q: "The first episode of EastEnders aired.", year: 1985 },
    { q: "Coronation Street first aired.", year: 1960 },
    { q: "Doctor Who first aired.", year: 1963 },
    { q: "Gavin & Stacey first aired.", year: 2007 },
    { q: "The Office (UK) first aired.", year: 2001 },
    { q: "The London Eye opened to the public.", year: 2000 },
    { q: "The first McDonald's opened in the UK.", year: 1974 },
    { q: "The Mars bar was first made, in Slough.", year: 1932 },
    { q: "Walkers crisps was founded.", year: 1948 },
    { q: "Red Bull went on sale.", year: 1987 },
    { q: "Magna Carta was sealed.", year: 1215 },
    { q: "The Battle of Hastings.", year: 1066 },
    { q: "The Great Fire of London.", year: 1666 },
    { q: "The Gunpowder Plot.", year: 1605 },
    { q: "Columbus first reached the Americas.", year: 1492 },
    { q: "Shakespeare was born.", year: 1564 },
    { q: "The American Declaration of Independence was signed.", year: 1776 },
    { q: "The French Revolution began with the storming of the Bastille.", year: 1789 },
    { q: "Queen Victoria died.", year: 1901 },
    { q: "Some women first got the vote in the UK.", year: 1918 },
    { q: "Everest was first climbed.", year: 1953 },
    { q: "The London Underground's first line opened.", year: 1863 },
    { q: "Leicester City won the Premier League at 5000-1.", year: 2016 },
    { q: "The Spice Girls announced Geri was leaving.", year: 1998 },
    { q: "The Millennium Bug didn't end the world.", year: 2000 },
    { q: "Barack Obama became US President.", year: 2009 },
    { q: "The Berlin Olympics where Jesse Owens won four golds.", year: 1936 },
    { q: "The first Glastonbury headlined by Beyoncé.", year: 2011 },
  ],

  trivia: [
    { q: "What's the capital of Canada?", options: ["Ottawa", "Toronto", "Vancouver", "Montreal"] },
    { q: "Which is the largest planet in the solar system?", options: ["Jupiter", "Saturn", "Neptune", "Earth"] },
    { q: "What's the chemical symbol for iron?", options: ["Fe", "Ir", "In", "I"] },
    { q: "Who wrote 'Romeo and Juliet'?", options: ["Shakespeare", "Dickens", "Marlowe", "Chaucer"] },
    { q: "Which band sang 'Wonderwall'?", options: ["Oasis", "Blur", "Pulp", "The Verve"] },
    { q: "Which band was Harry Styles in?", options: ["One Direction", "Take That", "JLS", "The Wanted"] },
    { q: "What's the smallest prime number?", options: ["2", "1", "3", "0"] },
    { q: "How many bones are in the adult human body?", options: ["206", "212", "198", "186"] },
    { q: "Which gas do plants absorb from the air?", options: ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"] },
    { q: "What's the currency of Japan?", options: ["Yen", "Won", "Yuan", "Ringgit"] },
    { q: "In which city is the Colosseum?", options: ["Rome", "Athens", "Naples", "Milan"] },
    { q: "What does a Geiger counter measure?", options: ["Radiation", "Earthquakes", "Wind speed", "Alcohol"] },
    { q: "Which is the hottest planet in the solar system?", options: ["Venus", "Mercury", "Mars", "Jupiter"] },
    { q: "How many minutes are in a day?", options: ["1,440", "1,240", "1,640", "1,400"] },
    { q: "What's the tallest mountain in the UK?", options: ["Ben Nevis", "Snowdon", "Scafell Pike", "Helvellyn"] },
    { q: "Platform 9¾ is at which London station?", options: ["King's Cross", "Euston", "Paddington", "Waterloo"] },
    { q: "What's the name of Batman's butler?", options: ["Alfred", "Jarvis", "Jeeves", "Albert"] },
    { q: "How big is a Nebuchadnezzar bottle of champagne?", options: ["15 litres", "3 litres", "6 litres", "30 litres"] },
    { q: "Which beer is brewed at St James's Gate?", options: ["Guinness", "Heineken", "Carling", "Stella Artois"] },
    { q: "Pimm's No. 1 is based on which spirit?", options: ["Gin", "Vodka", "Rum", "Whisky"] },
    { q: "Which fruit goes in a Bellini?", options: ["Peach", "Strawberry", "Mango", "Apricot"] },
    { q: "Who won the 2022 FIFA World Cup?", options: ["Argentina", "France", "Brazil", "Croatia"] },
    { q: "Who won Euro 2020 (played in 2021)?", options: ["Italy", "England", "Spain", "Denmark"] },
    { q: "How many points is the black ball worth in snooker?", options: ["7", "6", "5", "8"] },
    { q: "In tennis, what's a score of zero called?", options: ["Love", "Nil", "Duck", "Blank"] },
    { q: "Roughly how long is a marathon?", options: ["26.2 miles", "24 miles", "30 miles", "22.4 miles"] },
    { q: "Who is the Greek god of wine?", options: ["Dionysus", "Apollo", "Hermes", "Ares"] },
    { q: "What's the capital of Scotland?", options: ["Edinburgh", "Glasgow", "Aberdeen", "Dundee"] },
    { q: "What's the capital of Wales?", options: ["Cardiff", "Swansea", "Newport", "Bangor"] },
    { q: "What's the capital of New Zealand?", options: ["Wellington", "Auckland", "Christchurch", "Queenstown"] },
    { q: "What's the capital of Turkey?", options: ["Ankara", "Istanbul", "Izmir", "Antalya"] },
    { q: "What's the capital of Switzerland?", options: ["Bern", "Zurich", "Geneva", "Basel"] },
    { q: "Which element has the symbol K?", options: ["Potassium", "Krypton", "Calcium", "Kryptonite"] },
    { q: "How many teeth does an adult usually have?", options: ["32", "28", "30", "36"] },
    { q: "In Friends, what's the name of Ross's monkey?", options: ["Marcel", "Bubbles", "George", "Mr Monkey"] },
    { q: "What's the name of the bar in The Simpsons?", options: ["Moe's", "Barney's", "The Drunken Clam", "Paddy's"] },
    { q: "What's Del Boy's surname?", options: ["Trotter", "Boyce", "Trigger", "Tyler"] },
    { q: "Which film started the Marvel Cinematic Universe?", options: ["Iron Man", "Thor", "The Incredible Hulk", "Captain America"] },
    { q: "Who played Jack in Titanic?", options: ["Leonardo DiCaprio", "Brad Pitt", "Matt Damon", "Johnny Depp"] },
    { q: "What's the fastest land animal?", options: ["Cheetah", "Lion", "Pronghorn", "Greyhound"] },
    { q: "Which country does the mojito come from?", options: ["Cuba", "Mexico", "Brazil", "Spain"] },
    { q: "Which country does Heineken come from?", options: ["Netherlands", "Belgium", "Germany", "Denmark"] },
    { q: "Tequila is made from which plant?", options: ["Agave", "Cactus", "Sugar cane", "Aloe vera"] },
    { q: "What's a sommelier an expert in?", options: ["Wine", "Cheese", "Beer", "Cigars"] },
    { q: "Which liqueur is made from Scotch whisky, honey, herbs and spices?", options: ["Drambuie", "Baileys", "Cointreau", "Amaretto"] },
    { q: "What's the name of the pub in Emmerdale?", options: ["The Woolpack", "The Dingle Arms", "The Rovers Return", "The Bull"] },
    { q: "What's the bullseye worth in darts?", options: ["50", "25", "100", "60"] },
    { q: "What's the longest-running UK TV soap?", options: ["Coronation Street", "EastEnders", "Emmerdale", "Hollyoaks"] },
    { q: "Which UK city is known as the Granite City?", options: ["Aberdeen", "Edinburgh", "Leeds", "Belfast"] },
    { q: "How many players does a rugby union team have on the pitch?", options: ["15", "13", "11", "12"] },
    { q: "Which football club is nicknamed 'The Toffees'?", options: ["Everton", "Liverpool", "Aston Villa", "West Brom"] },
    { q: "How many hearts does an octopus have?", options: ["3", "1", "2", "8"] },
    { q: "What's the largest organ of the human body?", options: ["Skin", "Liver", "Brain", "Lungs"] },
    { q: "Which planet is closest to the Sun?", options: ["Mercury", "Venus", "Mars", "Earth"] },
    { q: "Which ocean is the Bermuda Triangle in?", options: ["Atlantic", "Pacific", "Indian", "Arctic"] },
    { q: "What's the name of the fairy in Peter Pan?", options: ["Tinker Bell", "Fairy Godmother", "Navi", "Silvermist"] },
    { q: "Who painted 'The Starry Night'?", options: ["Van Gogh", "Monet", "Picasso", "Dalí"] },
    { q: "How many sides does a 50p coin have?", options: ["7", "6", "8", "5"] },
    { q: "Which country has the most pyramids?", options: ["Sudan", "Egypt", "Mexico", "Peru"] },
    { q: "Which vitamin do we get from sunlight?", options: ["Vitamin D", "Vitamin C", "Vitamin A", "Vitamin B12"] },
  ],

  roleSets: [
    { title: "The Simpsons", roles: ["Homer", "Marge", "Bart", "Lisa", "Maggie", "Mr Burns", "Ned Flanders"], drink: "Homer" },
    { title: "Harry Potter", roles: ["Harry", "Hermione", "Ron", "Dumbledore", "Snape", "Hagrid", "Voldemort"], drink: "Voldemort" },
    { title: "On Love Island, who's…", roles: ["The bombshell", "The mug", "The villain", "The one cracking on with everyone", "The one in it for the followers", "The one crying on the terrace"], drink: "The mug" },
    { title: "At work, who's…", roles: ["The boss", "The one who steals your lunch", "The one always 'working from home'", "The office gossip", "The one who's always ill on Mondays", "The one who replies-all"], drink: "The one who's always ill on Mondays" },
    { title: "The Office", roles: ["David Brent", "Gareth", "Tim", "Dawn", "Keith", "Finchy"], drink: "David Brent" },
    { title: "Gavin & Stacey", roles: ["Gavin", "Stacey", "Smithy", "Nessa", "Pam", "Uncle Bryn", "Dawn"], drink: "Uncle Bryn" },
    { title: "The Inbetweeners", roles: ["Will", "Simon", "Jay", "Neil"], drink: "Jay" },
    { title: "At a wedding, who's…", roles: ["The one with the awful speech", "The one crying at the vows", "The one who pulls a bridesmaid", "The first on the dance floor", "The one asleep under a table", "The heckler"], drink: "The one asleep under a table" },
    { title: "On holiday, who's…", roles: ["The one who plans everything", "The one sunburnt on day one", "The one who loses their passport", "The one who pulls a local", "The one skint by day two", "The one who complains about the food"], drink: "The one sunburnt on day one" },
    { title: "Disney villains", roles: ["Scar", "Ursula", "Jafar", "Cruella", "Maleficent", "Captain Hook"], drink: "Cruella" },
    { title: "The Beatles", roles: ["John", "Paul", "George", "Ringo"], drink: "Ringo" },
    { title: "Which chocolate bar are you?", roles: ["Twix", "Bounty", "Snickers", "Mars", "Galaxy", "Kinder Bueno", "Crunchie"], drink: "Bounty" },
    { title: "Which dog are you?", roles: ["A Labrador", "A Chihuahua", "A Pug", "A Greyhound", "A Border Collie", "A Rottweiler", "A sausage dog"], drink: "A Chihuahua" },
    { title: "Which drink are you?", roles: ["A pint of lager", "A glass of red", "A double G&T", "A pint of Guinness", "A tequila shot", "An alcopop", "A lime and soda"], drink: "An alcopop" },
    { title: "Game of Thrones", roles: ["Jon Snow", "Daenerys", "Tyrion", "Cersei", "Arya", "Joffrey", "Hodor"], drink: "Joffrey" },
    { title: "At a festival, who's…", roles: ["The one who never finds the tent", "The one who's front row for everything", "The one who refuses to use the toilets", "The one who's lost by 6pm", "The one who brought a flag", "The one who goes home early"], drink: "The one who's lost by 6pm" },
    { title: "After closing time, who's…", roles: ["The one snogging a stranger", "The one crying in the toilets", "The one fighting a kebab", "The one who's lost their shoes", "The one who goes home with the bouncer", "The one texting their ex"], drink: "The one texting their ex", filthy: true },
    { title: "At the orgy, who's…", roles: ["The one who organised it", "The one watching from the corner", "The one who brought snacks", "The one who leaves first", "The one who's done this before", "The one who keeps their socks on"], drink: "The one who keeps their socks on", filthy: true },
    { title: "In a relationship, who's…", roles: ["The clingy one", "The jealous one", "The one who never texts back", "The one who's always on their phone", "The one who cheats", "The one who's too good for them"], drink: "The one who cheats", filthy: true },
  ],

  teeIdeas: [
    "a seagull stealing chips", "your boss on a Monday", "a sheep at a rave", "a haunted pint glass",
    "a Greggs sausage roll in love", "your ideal partner, badly", "the group chat as a monster", "a hungover sun",
    "a dog that pays taxes", "a very tired Santa", "a sexy traffic cone", "the worst tattoo ever",
    "a pigeon on a date", "a baby in a business suit", "a lobster in a hot tub", "your nan as a superhero",
    "the moon having a bad day", "a cheese with a secret", "a burger on holiday", "the host as a dinosaur",
    "a fridge at 3am", "a jacket potato with a six-pack", "a bee with a hangover", "a disappointed goldfish",
    "your future self", "a toaster that's seen too much", "a cow on a stag do", "a cactus giving a hug",
    "an angry croissant", "a llama in a nightclub", "the last chip in the bag", "a banana at the gym",
    "a snowman in summer", "a sad clown at a wedding", "a frog in a wedding dress", "a lamp post with dreams",
  ],

  stiQuestions: [
    "What's your go-to takeaway order?",
    "What's the best present you've ever received?",
    "Describe your first car.",
    "What's your dream job?",
    "What would you do with a free afternoon?",
    "What's your signature dish?",
    "What's something you've been meaning to fix at home?",
    "What's your favourite way to spend a Saturday morning?",
    "What did you want to be when you grew up?",
    "What's your hidden talent?",
    "What's the best thing you've bought this year?",
    "Describe your childhood bedroom.",
    "What's your favourite holiday memory?",
    "What's the worst chore, and why?",
    "What would your last meal be?",
    "What's your favourite thing about where you live?",
    "What's your favourite song to sing in the car?",
    "Describe your dream house.",
    "What's the best compliment you've ever had?",
    "What's something you're really good at?",
    "Describe your ideal pet.",
    "What's the first thing you do when you get home from work?",
    "What's your favourite biscuit, and why?",
    "What's the best meal you've ever had?",
    "Give some advice to a new parent.",
    "Review your local park.",
    "What do you always pack for a holiday?",
    "Describe your perfect birthday.",
    "What's your favourite season, and why?",
    "Tell us about your favourite teacher.",
  ],

  stiContexts: [
    "a message left for their ex's new partner",
    "a comment on a hospital's Facebook page",
    "a review of a prison",
    "a speech at a divorce party",
    "a post on a nudist forum",
    "a text to their mum after losing their virginity",
    "the caption on a photo of a car crash",
    "a statement read out in court",
    "a comment under a news story about a missing tortoise",
    "a Google review of a sperm bank",
    "a message in a bottle found by the coastguard",
    "a leaving card for a colleague who got fired",
    "a Tinder bio",
    "a tattoo on their lower back",
    "a speech at a retirement home talent show",
    "a sign held up at a protest",
    "a comment on their dad's Facebook post announcing his new girlfriend",
    "a TripAdvisor review of a swingers' club",
    "a text to a drug dealer",
    "a wedding vow",
    "the message on a condolence card",
    "an entry in their teenage diary",
    "a customer complaint to Ann Summers",
    "a post in a Facebook group for divorced dads",
    "a message on a gravestone",
    "a voicemail left for a dentist",
    "a review of a haunted house tour",
    "a speech to the police negotiator",
    "a Christmas round-robin letter",
  ],

  lines: {
    welcome: [
      "Welcome to Last Orders. Look around you. These are your friends. I'm so sorry.",
      "Good evening. Tonight's game is sponsored by bad decisions and the NHS.",
      "{name}, {other}. You two look like you've already started. Good.",
      "Welcome to Last Orders. There are no winners here. Only people who drank slightly less.",
    ],
    drink: [
      "{name}, drink. Think of it as hydration with consequences.",
      "{name}, drink. The group has spoken, and the group hates you.",
      "Sip up, {name}. You're doing brilliantly. At drinking. Everything else, less so.",
      "{name}, drink. Your mother would be proud. Well. She'd be something.",
      "{name}. Drink. It's not a punishment, it's a lifestyle.",
    ],
    none: [
      "Nobody drinks this round. I'm as disappointed as your parents.",
      "No drinks? Right. I'll remember this.",
    ],
  },
};
