// Prompt decks for each round type. Add your own in-jokes here!

export const LIKELY = [
  "Who is most likely to text their ex tonight?",
  "Who is most likely to fall asleep at the party?",
  "Who is most likely to become famous?",
  "Who is most likely to get lost on the way home?",
  "Who is most likely to start a fight with a bouncer?",
  "Who is most likely to cry at a film?",
  "Who is most likely to survive a zombie apocalypse?",
  "Who is most likely to be first to the dance floor?",
  "Who is most likely to order a kebab at 3am?",
  "Who is most likely to forget their own birthday?",
  "Who is most likely to get a questionable tattoo on holiday?",
  "Who is most likely to secretly know all the words to a boyband album?",
  "Who is most likely to lose their phone tonight?",
  "Who is most likely to end up on a reality TV show?",
  "Who is most likely to befriend a stranger in the toilets?",
  "Who is most likely to still be up at sunrise?",
  "Who is most likely to reply-all by accident?",
  "Who is most likely to get kicked out of a museum?",
  "Who is most likely to start a band and never play a gig?",
  "Who is most likely to have a secret second family?",
  "Who is most likely to cheat at Monopoly?",
  "Who is most likely to adopt 10 cats?",
  "Who is most likely to say 'one more drink' and mean fifteen?",
  "Who is most likely to join a cult by accident?",
  "Who is most likely to get married in Vegas?",
  "Who is most likely to ask for the aux cord and play something awful?",
  "Who is most likely to become a millionaire?",
  "Who is most likely to be arrested for something ridiculous?",
  "Who is most likely to fall over on a night out?",
  "Who is most likely to have the worst search history?",
];

export const NHIE = [
  "Never have I ever sent a text to the wrong person.",
  "Never have I ever pretended to be ill to skip work.",
  "Never have I ever fallen asleep on public transport and missed my stop.",
  "Never have I ever lied about my age.",
  "Never have I ever been kicked out of a bar.",
  "Never have I ever stalked an ex on social media.",
  "Never have I ever eaten food off the floor.",
  "Never have I ever cried in a work meeting.",
  "Never have I ever re-gifted a present.",
  "Never have I ever pretended to know a song at karaoke.",
  "Never have I ever ghosted someone.",
  "Never have I ever had a crush on a friend's sibling.",
  "Never have I ever lied in this game.",
  "Never have I ever broken something and blamed someone else.",
  "Never have I ever been on a blind date.",
  "Never have I ever walked into a glass door.",
  "Never have I ever sung in the shower loud enough for neighbours to hear.",
  "Never have I ever snuck into a cinema screen I didn't pay for.",
  "Never have I ever forgotten someone's name mid-conversation.",
  "Never have I ever drunk-ordered something online.",
  "Never have I ever gone a whole weekend in pyjamas.",
  "Never have I ever been in a fight.",
  "Never have I ever lost a shoe on a night out.",
  "Never have I ever faked a phone call to escape a conversation.",
  "Never have I ever cut my own hair and regretted it.",
  "Never have I ever called a teacher 'Mum' or 'Dad'.",
  "Never have I ever read someone else's messages without them knowing.",
  "Never have I ever lied about reading a book.",
];

export const WYR = [
  ["Always be 10 minutes late", "Always be 20 minutes early"],
  ["Only drink warm beer forever", "Only drink flat fizzy drinks forever"],
  ["Have a rewind button for your life", "Have a pause button for your life"],
  ["Be able to fly", "Be invisible"],
  ["Fight one horse-sized duck", "Fight 100 duck-sized horses"],
  ["Never use social media again", "Never watch TV again"],
  ["Know how you'll die", "Know when you'll die"],
  ["Live without music", "Live without films"],
  ["Have hiccups for the rest of your life", "Always feel like you're about to sneeze"],
  ["Be the funniest person in the room", "Be the smartest person in the room"],
  ["Eat pizza for every meal", "Never eat pizza again"],
  ["Have your search history made public", "Have your texts made public"],
  ["Go to the past", "Go to the future"],
  ["Sing everything you say", "Dance everywhere you walk"],
  ["Have a personal chef", "Have a personal chauffeur"],
  ["Lose your phone", "Lose your wallet"],
  ["Only whisper", "Only shout"],
  ["Be stuck in a lift with your boss", "Be stuck in a lift with your ex"],
  ["Have unlimited free flights", "Have unlimited free food"],
  ["Give up cheese", "Give up chocolate"],
  ["Hear every thought of the people around you", "Have everyone hear your thoughts"],
  ["Be a famous musician", "Be a famous athlete"],
  ["Have a pet dragon", "Have a pet unicorn"],
  ["Wake up at 5am every day", "Go to bed at 5am every day"],
];

// Quip rounds: everyone answers, everyone votes. "___" is the blank.
export const QUIPS = [
  "The worst thing to hear from your pilot: \"___\"",
  "A terrible name for a pub: ___",
  "What the Queen really kept in her handbag: ___",
  "The real reason the dinosaurs died out: ___",
  "A bad thing to shout at a wedding: \"___\"",
  "The worst flavour of crisps: ___",
  "Rejected slogan for a dating app: \"___\"",
  "What you should never say to a bouncer: \"___\"",
  "The secret ingredient in Grandma's stew: ___",
  "A terrible superpower: ___",
  "The worst thing to find in your hotel bed: ___",
  "What aliens would think our national sport is: ___",
  "A great name for a boat: ___",
  "The worst thing to say at a job interview: \"___\"",
  "A strange thing to collect: ___",
  "The worst theme for a stag or hen do: ___",
  "What the group chat is really called: ___",
  "The real reason you're late: \"___\"",
  "A bad name for a perfume: ___",
  "Something you should never Google at work: ___",
  "The next big fitness craze: ___",
  "A controversial pizza topping: ___",
  "A terrible thing to write in a birthday card: \"___\"",
  "What your dog is actually thinking: \"___\"",
  "The worst possible first line of a best-man speech: \"___\"",
  "The 11th commandment: Thou shalt not ___",
  "What's actually at the bottom of the ocean: ___",
  "An unlikely thing to be arrested for: ___",
  "A rubbish reality TV show: ___",
  "The worst thing to hear from the next toilet cubicle: \"___\"",
];

// Social rounds: no input, just a rule everyone follows.
export const SOCIAL = [
  "Everyone wearing black drinks!",
  "The last person to touch their nose drinks. GO!",
  "Waterfall! Everyone drinks until the person on the host's left stops.",
  "Everyone who has been abroad this year drinks.",
  "Youngest player drinks 2 sips.",
  "Oldest player hands out 3 sips.",
  "Anyone with a phone battery under 30% drinks.",
  "Cheers! Everyone drinks together.",
  "The tallest person drinks, then picks someone to join them.",
  "Anyone who has been single this whole year drinks.",
  "Everyone who has a pet drinks. Dog people drink twice.",
  "Category: pub names. Go round the room — first to hesitate drinks!",
  "Rhyme time: host says a word, go round rhyming. First to fail drinks.",
  "Thumb master: the last person to put their thumb on the table drinks.",
  "Everyone who's been to a festival drinks.",
  "The person with the most unread notifications drinks.",
  "Everyone swaps seats. The last to sit down drinks.",
  "Anyone who laughed during the last round drinks.",
];

export const ROUND_INFO = {
  likely: { title: "Most Likely To", emoji: "👉", rules: "Vote for the friend who fits best. The most-voted drinks 2 sips. Vote with the crowd for 100 points." },
  nhie:   { title: "Never Have I Ever", emoji: "🙊", rules: "Be honest! If you have, you drink 1 sip — but get 50 points for confessing." },
  wyr:    { title: "Would You Rather", emoji: "⚖️", rules: "Pick a side. The minority drinks 1 sip, the majority scores 100 points." },
  quip:   { title: "Quip Clash", emoji: "✍️", rules: "Write the funniest answer, then vote for your favourite. 100 points per vote. Zero votes? Drink 2 sips." },
  social: { title: "Social", emoji: "🍻", rules: "Everybody follow the rule on screen!" },
};

export function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
